const movies = [
    { id: "1", title: "Iron Man (2008)", description: "After being captured in hostile territory, billionaire and tech genius Tony Stark uses his brilliant mind to build a suit of armor that changes his life forever. With a newfound purpose, he becomes the iconic hero Iron Man and fights for justice – but his greatest battle might be against himself.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Jon Favreau<br><br><b>Actors</b><br>Robert Downey Jr, Jon Favreau<br>", trailer: "https://www.youtube.com/embed/8ugaeA-nMTc"},
    { id: "2", title: "Captain America: The First Avenger (2011)", description: `In an era marked by war, the humble Steve Rogers transforms into the super-soldier Captain America. Armed with an unbreakable shield and a heart of steel, he fights against a sinister enemy threatening the future of the world. An epic journey begins that will define a legend.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Joe Johnson<br><br><b>Actors</b><br>Chris Evans, Hayley Atwell, Sebastian Stan`, trailer: "https://www.youtube.com/embed/JerVrbLldXw"},  
    { id: "3", title: "Thor (2011)", description: "In a world where gods walk among humans, the mighty Thor is banished to Earth without his powers. To prove his worth, he must overcome not only his enemies but also his own arrogance. A cosmic journey of power, responsibility, and courage awaits.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Kenneth Branagh<br><br><b>Actors</b><br>Chris Hemsworth, Natalie Portman, Idris Elba", trailer: "https://www.youtube.com/embed/JOddp-nlNvQ"},  
    { id: "4", title: "The Avengers (2012)", description: "Earth’s mightiest heroes unite for the first time to protect the planet from Loki and his alien army. Featuring iconic team dynamics, epic battles, and the formation of a legendary team, the Avengers prove they are stronger together against an unstoppable threat.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Actors</b><br>Chris Evans, Chris Hemsworth, Scarlet Johanson, Robert Downey Jr, Mark Ruffalo, Samuel L. Jackson<br>", trailer: "https://www.youtube.com/embed/hL8AuX7MBc4"},  
    { id: "5", title: "Ironman 2", description: "Tony Stark faces growing pressures as his identity as Iron Man becomes public knowledge. With new enemies emerging and the government demanding his technology, Stark must balance his responsibilities as a hero with the challenges of his personal life, all while dealing with a formidable new foe.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Jon Favreau<br><br><b>Actors</b><br>Scarlet Johanson, Robert Downey Jr, Samuel L. Jackson<br>", trailer: "https://www.youtube.com/embed/BoohRoVA9WQ"},  
    { id: "6", title: "Captain America: The Winter Soldier", description: "In Captain America: The Winter Soldier, Steve Rogers battles not only a mysterious assassin known as the Winter Soldier but also faces corruption within S.H.I.E.L.D. itself. With thrilling action and unexpected allies, Cap must decide who he can trust in a world full of secrets and deception.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Anthony Russo, Joe Russo<br><b>Actors</b><br>Chris Evans, Sebastian Stan, Samuel L. Jackson<br>", trailer: "https://www.youtube.com/embed/tbayiPxkUMM"},  
    { id: "7", title: "Thor: The Dark World", description: "Thor faces a vengeful ancient race led by the ruthless Malekith, who seeks to plunge the universe into eternal darkness. With his world in peril, Thor must unite with old allies—and a surprising adversary—to save Asgard and all the Nine Realms from annihilation.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Actors</b><br>Chris Hemsworth, Natalie Portma, Idris Elba", trailer: "https://www.youtube.com/embed/npvJ9FTgZbM"},  
    { id: "8", title: "Avengers: Age of Ultron", description: "Age of Ultron sees the Avengers facing their most complex adversary yet—Ultron, an AI gone rogue with plans for human extinction. As the team rallies to stop Ultron’s global destruction, they are tested like never before, encountering new allies, darker forces, and the terrifying potential of technology.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Actors</b>Chris Evans, Chris Hemsworth, Scarlet Johanson, Robert Downey Jr, Mark Ruffalo, Samuel L. Jackson<br>", trailer: "https://www.youtube.com/embed/tmeOjFno6Do"},  
    { id: "9", title: "Iron Man 3", description: "Iron Man 3 follows Tony Stark as he confronts his most dangerous adversary yet, the mysterious Mandarin. As his world is torn apart, Stark embarks on a journey of self-discovery, pushing his ingenuity and resilience to the limits to protect those he loves.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Shane Black<b><br><br>Actors</b>Robert Downey Jr<br>", trailer: "https://www.youtube.com/embed/Ke1Y3P9D0Bc"},  
    { id: "10", title: "Captain America: Civil War", description: "Civil War pits hero against hero as ideological differences split the Avengers team. With friendships on the line, Captain America and Iron Man lead their factions in a high-stakes clash that will change the Marvel Universe forever. Loyalties are tested, and no one emerges unscathed.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Anthony Russo, Joe Russo<br><br><b>Actors</b>Chris Evans, Chris Hemsworth, Scarlet Johanson, Robert Downey Jr, Mark Ruffalo, Sebastian Stan, Chadwick Boseman<br>", trailer: "https://www.youtube.com/embed/dKrVegVI0Us"},  
    { id: "11", title: "Thor: Ragnarok", description: "Imprisoned on the other side of the cosmos, Thor finds himself stripped of his mighty hammer and racing against time to prevent the ruthless goddess Hela from destroying Asgard. Teaming up with unlikely allies, including the Hulk and the unpredictable Loki, Thor embarks on an electrifying quest across vibrant worlds, facing challenges that will redefine what it means to be a hero and the protector of his realm.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Actors</b><br>Chris Hemsworth, Natalie Portman, Mark Ruffalo, Idris Elba<br>", trailer: "https://www.youtube.com/embed/ue80QwXMRHg"},  
    { id: "12", title: "Avengers: Infinity War", description: "Infinity War follows the Avengers and their allies as they join forces to prevent Thanos, the Mad Titan, from gathering all six Infinity Stones. With the fate of the universe in their hands, heroes must make sacrifices and face devastating consequences in this epic, action-packed showdown.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Anthony Russo, Joe Russo<br><br><b>Actors</b><br>Chris Evans, Chris Hemsworth, Scarlet Johanson, Robert Downey Jr, Mark Ruffalo, Sebastian Stan, Samuel L. Jackson<br>", trailer: "https://www.youtube.com/embed/6ZfuNTqbHE8"},  
    { id: "13", title: "Dr. Strange", description: "When brilliant neurosurgeon Stephen Strange loses the use of his hands in a tragic accident, he embarks on a desperate journey to find healing and hope. But what he discovers goes far beyond the limits of medicine. Guided by mystics in the far East, he unlocks the secrets of magic and alternate dimensions, stepping into a world where reality itself can be bent. As a powerful threat looms, Strange must choose between his ego and his duty to protect the universe.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Actors</b><br>Benedict Cumberbatch, Chiwetel Ejiofor, Benedict Wong", trailer: "https://www.youtube.com/embed/HSzx-zryEgM"},  
    { id: "14", title: "Ant-Man", description: "Ex-con Scott Lang never imagined he’d become a hero, but when he’s handed a suit that lets him shrink down to the size of an ant, his life is turned upside down. With the fate of the world hanging in the balance, he teams up with a scientist's daughter to master his new powers. Taking on towering challenges, Scott realizes that even the smallest hero can have the biggest impact.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Actors</b><br>Paul Rudd, Michael Douglass, Corey Stoll, Evangline Lilly, Anthony Mackie, Michael Pena, David Dastmalchian", trailer: "https://www.youtube.com/embed/pQdKf3MneyI"},  
    { id: "15", title: "Black Panther", description: "Returning to the hidden, technologically advanced nation of Wakanda, T’Challa assumes the mantle of king and protector, only to face challenges that threaten both his kingdom and the world beyond. An outsider emerges, claiming his own right to the throne and dragging Wakanda into the global spotlight. To secure his people’s future and his father’s legacy, T’Challa must confront formidable foes and unlock the true power of the Black Panther.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Ryan Coogler<br><br><b>Actors</b><br>Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira, Martin Freeman", trailer: "https://www.youtube.com/embed/xjDjIWPwcPU"},  
    { id: "16", title: "Avengers: Endgame", description: "The surviving Avengers embark on a daring mission to undo the damage caused by Thanos. With time running out, the team risks everything in a battle for redemption, friendship, and hope, culminating in one of the most powerful and emotional finales in cinematic history.<br><br><b>Producer</b><br>Kevin Feige<br><br><b>Director</b><br>Anthony Russo, Joe Russo<br><br><b>Actors</b><br>Chris Evans, Chris Hemsworth, Scarlet Johanson, Robert Downey Jr, Mark Ruffalo, Chadwick Boseman, Sebastian Stan, Samuel L. Jackson", trailer: "https://www.youtube.com/embed/h7gvFravm4A"},  
    { id: "17", title: "The Lord of the Rings: The fellowship of the Ring", description: "A young hobbit named Frodo Baggins is thrust into an ancient struggle when he inherits a mysterious ring. Unbeknownst to him, this is the One Ring, forged by the Dark Lord Sauron to rule all. As darkness stirs, Frodo joins a fellowship of heroes—including a ranger, an elf, a dwarf, and a wizard—to journey to Mount Doom and destroy the ring before Sauron reclaims his power. A tale of courage, friendship, and destiny begins.<br><br><b>Producer</b><br>Peter Jackson<br><br><b>Director</b>Peter Jackson<br><br><b>Actors</b><br>Elijah Wood, Ian McKellen, Viggo Mortensen, Orlando Bloom, John Rhys-Davies, Sean Bean, Andy Serkis", trailer: "https://www.youtube.com/embed/V75dMMIW2B4"},  
    { id: "18", title: "The Lord of the Rings: The Two Towers", description: "As the fellowship is broken, the heroes of Middle-earth face the encroaching armies of Sauron and the eerie threat of Saruman's dark fortress, Isengard. With the ring weighing heavily on Frodo and his loyal friend Sam, they face dangers both seen and unseen. Hope rests on the bond between friends and the courage to stand against impossible odds. The battle for Middle-earth has only begun.<br><br><b>Producer</b><br>Peter Jackson<br><br><b>Director</b>Peter Jackson<br><br><b>Actors</b><br>Elijah Wood, Ian McKellen, Viggo Mortensen, Orlando Bloom, John Rhys-Davies, Andy Serkis", trailer: "https://www.youtube.com/embed/LbfMDwc4azU"},  
    { id: "19", title: "The Lord of the Rings: The return of the King", description: "With the armies of Mordor marching upon Gondor, humanity’s last stand begins. Aragorn, the rightful king, must rally his allies and fulfill his destiny to lead the people of Middle-earth. Meanwhile, Frodo and Sam's harrowing journey to Mount Doom nears its end, but with the ring’s influence growing, the final struggle will test them in ways they never imagined. The fate of Middle-earth hangs by a thread in this epic conclusion.<br><br><b>Producer</b><br>Peter Jackson<br><br><b>Director</b>Peter Jackson<br><br><b>Actors</b><br>Elijah Wood, Ian McKellen, Viggo Mortensen, Orlando Bloom, John Rhys-Davies, Andy Serkis", trailer: "https://www.youtube.com/embed/y2rYRu8UW8M"},  
    { id: "20", title: "The Hobbit: An unexpected journey", description: "When Bilbo Baggins, a quiet and unassuming hobbit, is unexpectedly whisked away on an adventure by a band of dwarves and the mysterious wizard Gandalf, he finds himself far from the comforts of home. Facing trolls, goblins, and a terrifying dragon named Smaug, Bilbo discovers courage and cunning he never knew he had. The journey of a lifetime begins, setting in motion a tale that will change Middle-earth forever.<br><br><b>Producer</b><br>Peter Jackson<br><br><b>Director</b>Peter Jackson, Zane Weiner<br><br><b>Actors</b><br>Martin Freeman, Ian McKellen, Ken Stott, Graham McTavish, Lee Pace, Ecangeline Lilly, Benedict Cumberbatch", trailer: "https://www.youtube.com/embed/JTSoD4BBCJc"},  
    { id: "21", title: "The Hobbit: The desolation of Smaug", description: "Having narrowly escaped previous encounters, Bilbo and his companions continue their journey to the Lonely Mountain, where the fierce dragon Smaug lies in wait. Along the way, they face treacherous forests, giant spiders, and ruthless enemies. But the most dangerous test awaits within the mountain itself, where Bilbo’s bravery—and a small ring he discovered—could be the key to survival.<br><br><b>Producer</b><br>Peter Jackson<br><br><b>Director</b>Peter Jackson, Zane Weiner<br><br><b>Actors</b><br>Martin Freeman, Ian McKellen, Ken Stott, Graham McTavish, Lee Pace, Ecangeline Lilly, Benedict Cumberbatch", trailer: "https://www.youtube.com/embed/OPVWy1tFXuc"},  
    { id: "22", title: "The Hobbit: The battle of the five armies", description: "With Smaug unleashed upon the people of Lake-town, chaos reigns, and tensions rise as armies from across Middle-earth descend upon the Lonely Mountain. As greed and alliances threaten to tear the world apart, Bilbo must make a choice that will shape the future of all. Amid betrayal, bravery, and heartbreak, the fate of Middle-earth stands on the edge of a blade.<br><br><b>Producer</b><br>Peter Jackson<br><br><b>Director</b>Peter Jackson, Zane Weiner<br><br><b>Actors</b><br>Martin Freeman, Ian McKellen, Ken Stott, Graham McTavish, Lee Pace, Ecangeline Lilly, Benedict Cumberbatch", trailer: "https://www.youtube.com/embed/iVAgTiBrrDA"},  
    { id: "23", title: "HARRY POTTER AND THE SORCERER'S STONE", description: "Young Harry Potter, living a dull life with his neglectful aunt and uncle, discovers he is, in fact, a wizard. Whisked away to Hogwarts School of Witchcraft and Wizardry, he uncovers secrets about his past and a world of magic he never knew existed. As Harry settles into his new life, he learns of a powerful stone that grants immortality—and finds himself face-to-face with the dark forces that threaten him and all he holds dear.<br><br><b>Producer</b><br>David Heyman<br><br><b>Director</b><br>Chris Columbus<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Richard Harris, Maggie Smith, Robbie Coltrane, Alan Rickman<br>", trailer: "https://www.youtube.com/embed/mNgwNXKBEW0"},  
    { id: "24", title: "HARRY POTTER AND THE CHAMBER OF SECRETS", description: "Returning to Hogwarts for his second year, Harry discovers a series of mysterious attacks plaguing the school. With whispers of a dark legend, the Chamber of Secrets, being unleashed, Harry and his friends must unravel the truth behind the attacks before it's too late. Strange messages, a mysterious diary, and a deadly creature lurking in the shadows make for a suspense-filled year at Hogwarts.<br><br><b>Producer</b><br>David Heyman<br><br><b>Director</b><br>Chris Columbus<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Maggie Smith, Robbie Coltrane, Alan Rickman<br>", trailer: "https://www.youtube.com/embed/1bq0qff4if8"},  
    { id: "25", title: "HARRY POTTER AND THE PRISONER OF AZKABAN", description: "When the infamous prisoner Sirius Black escapes from Azkaban, the wizarding world is on high alert. Harry learns that Black, a close ally of Voldemort, may be coming for him. As dark secrets from the past emerge, Harry, Hermione, and Ron face time-traveling adventures, new friendships, and an unexpected revelation about loyalty, fear, and family.<br><br><b>Producer</b><br>David Heyman<br><br><b>Director</b><br>Alfonso Cuarón<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Maggie Smith, Robbie Coltrane, Alan Rickman<br>", trailer: "https://www.youtube.com/embed/1AxgztbYDbs"},  
    { id: "26", title: "HARRY POTTER AND THE GOBLET OF FIRE", description: "The Triwizard Tournament, a dangerous magical competition, comes to Hogwarts, and Harry is unexpectedly chosen to participate. Facing deadly challenges, international rivalries, and mysterious threats, Harry’s skills and courage are pushed to the limit. But the tournament’s grand finale holds a chilling revelation—the return of Lord Voldemort, changing the wizarding world forever.<br><br><b>Producer</b><br>David Heyman<br><br><b>Director</b><br>Mike Newell<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Maggie Smith, Robbie Coltrane, Alan Rickman, Ralph Fiennes<br>", trailer: "https://www.youtube.com/embed/3EGojp4Hh6I"},  
    { id: "27", title: "HARRY POTTER AND THE ORDER OF THE PHOENIX", description: "As Voldemort's return becomes undeniable, Harry faces resistance from the Ministry of Magic, which refuses to believe him. He forms Dumbledore's Army with his friends to prepare for the dark times ahead. Amid a prophecy that foretells his destiny, battles of wills, and secrets about his connection to Voldemort, Harry learns the true strength of unity and the power of standing up for what’s right.<br><br><b>Producer</b><br>David Heyman<br><br><b>Director</b><br>David Yates<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Maggie Smith, Robbie Coltrane, Alan Rickman, Ralph Fiennes<br>", trailer: "https://www.youtube.com/embed/y6ZW7KXaXYk"},  
    { id: "28", title: "HARRY POTTER AND THE HALF-BLOOD PRINCE", description: "As Voldemort's grip on the wizarding world tightens, Harry and Dumbledore delve into the dark wizard's past to unlock the secrets to his power. Together, they uncover the existence of Horcruxes, dark objects that hold pieces of Voldemort’s soul. But as danger looms and losses hit close to home, Harry must come to terms with his destiny and the path that lies before him.<br><br><b>Producers</b><br>David Heyman, David Barron<br><br><b>Director</b><br>David Yates<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Maggie Smith, Robbie Coltrane, Alan Rickman, Ralph Fiennes<br>", trailer: "https://www.youtube.com/embed/sg81Lts5kYY"},  
    { id: "29", title: "HARRY POTTER AND THE DEATHLY HALLOWS: PART 1", description: "Harry, Ron, and Hermione leave Hogwarts behind to embark on a quest to destroy Voldemort’s Horcruxes. Facing isolation, fear, and the constant threat of capture, their bond is tested like never before. As they dig deeper into the mysteries surrounding Voldemort’s immortality, a dangerous chase and the shadow of sacrifice bring them closer to their final confrontation.<br><br><b>Producers</b><br>David Heyman, David Barron, J.K. Rowling<br><br><b>Director</b><br>David Yates<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Maggie Smith, Robbie Coltrane, Alan Rickman, Ralph Fiennes<br>", trailer: "https://www.youtube.com/embed/MlbsA8PyAOg"},  
    { id: "30", title: "HARRY POTTER AND THE DEATHLY HALLOWS: PART 2", description: "The epic conclusion to Harry’s journey sees him return to Hogwarts, where an all-out war rages. With Voldemort’s forces closing in, Harry must make the ultimate sacrifice to defeat the Dark Lord. Facing death, bravery, and the truth of his own destiny, Harry discovers that hope, love, and friendship are the most powerful magic of all. The battle for the wizarding world comes to a breathtaking, unforgettable end.<br><br><b>Producers</b><br>David Heyman, David Barron, J.K. Rowling<br><br><b>Director</b><br>David Yates<br><br><b>Actors</b><br>Daniel Radcliffe, Emma Watson, Rupert Grint, Maggie Smith, Robbie Coltrane, Alan Rickman, Ralph Fiennes<br>", trailer: "https://www.youtube.com/embed/mObk5XD8udk"},  
    { id: "100", title: "Gladiator II", description: "Years after Maximus’s heroic sacrifice, a new warrior rises to confront a fractured empire. With Rome caught in political turmoil, this fearless hero is drawn into a struggle for power, honor, and revenge. The shadow of Maximus’s legacy looms large, inspiring fierce alliances and dangerous enemies. As battles erupt and loyalties are tested, the path to victory is paved with betrayal, vengeance, and the ultimate quest for glory.<br><br><b>Producer</b><br>David Heyman<br><br><b>Director</b><br>Chris Columbus<br><br><b>Actors</b><br>Paul Mescal, Pedro Pescal, Connie Nielsen, Denzel Washington<br>", trailer: "https://www.youtube.com/embed/Ts0N8swyWFI"},  
  ];

function getQueryParam(param) {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get(param)
}

const movieId = getQueryParam("id");
console.log("Movie ID from URL:", movieId);

const selectedMovie = movies.find(movie => movie.id === movieId);
console.log("Selected Movie:", selectedMovie);

if (selectedMovie) {
    console.log('Selected movie:', selectedMovie);
    document.getElementById("movie-title").textContent = selectedMovie.title;
    document.getElementById("movie-description").innerHTML = selectedMovie.description;
    document.getElementById("movie-trailer").src = selectedMovie.trailer;
    } else {
    console.error('Movie not found for id:', movieId);
}

const button = document.querySelector('.featured-button'); 

if (button) { 
    button.addEventListener('click', function() {
        const buttonMovieId = this.getAttribute('data-id');
        
        // Navigate to movie-page.html with the selected movie ID
        if (buttonMovieId) {
            window.location.href = `movie-page.html?id=${buttonMovieId}`;
        } else {
            console.error("Movie ID not found for button.");
        }
    });
} else {
    console.warn('Button with class "featured-button" not found on the page.');
}

// Seating

const seats = document.querySelectorAll(".row .seat:not(.occupied)");
  const count = document.getElementById("count");
  const total = document.getElementById("total");
  const ticketPrice = 10; 

  function updateSelectedCount() {
    const selectedSeats = document.querySelectorAll(".row .seat.selected");
    const selectedSeatsCount = selectedSeats.length;

    // Update the count and total cost
    count.textContent = selectedSeatsCount;
    total.textContent = selectedSeatsCount * ticketPrice;
  }

  // Seat click event
  seats.forEach(seat => {
    seat.addEventListener("click", () => {
      seat.classList.toggle("selected");
      updateSelectedCount();
    });
  });

  // Initialize count and total on page load
  updateSelectedCount();
  